# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[9.6742e+19, 3.0756e-41, 5.7453e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3733e-14, 6.4076e+07, 2.0706e-19],
        [7.3909e+22, 2.4176e-12, 1.1625e+33],
        [8.9605e-01, 1.1632e+33, 5.6003e-02]])


Construct a randomly initialized matrix

In [28]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2641, 0.6887, 0.0562],
        [0.5656, 0.2232, 0.8009],
        [0.1723, 0.5200, 0.2870],
        [0.0709, 0.6406, 0.4079],
        [0.7797, 0.8896, 0.6748]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [29]:
x[1:3] = 2
print(x)

tensor([[0.2641, 0.6887, 0.0562],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.0709, 0.6406, 0.4079],
        [0.7797, 0.8896, 0.6748]])


# Assignment

1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [7]:
tensor = torch.rand(2,17)
print(tensor)

tensor([[0.4455, 0.7030, 0.3774, 0.0725, 0.9566, 0.5424, 0.2236, 0.0501, 0.4140,
         0.3619, 0.3682, 0.1487, 0.3752, 0.4694, 0.0815, 0.2656, 0.4446],
        [0.7791, 0.6347, 0.8299, 0.5237, 0.1301, 0.5214, 0.7383, 0.8351, 0.3166,
         0.9007, 0.7631, 0.5815, 0.5498, 0.9321, 0.0524, 0.1503, 0.3904]])


In [26]:
tensor = torch.FloatTensor(3,1)
print(tensor)

tensor([[1.6173e+25],
        [4.5685e-41],
        [9.6940e+19]])


In [12]:
tensor = torch.LongTensor(5,2,1)
print(tensor)

tensor([[[140026291030984],
         [ 94267567292032]],

        [[140025452174944],
         [ 94267563823696]],

        [[    -4294967296],
         [              3]],

        [[              0],
         [              3]],

        [[140025466962400],
         [              0]]])


In [13]:
tensor[0:len(x)]=7
print(tensor)

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [23]:
tensor = torch.zeros(5).byte()
print(tensor)

tensor([0, 0, 0, 0, 0], dtype=torch.uint8)


In [24]:
tensor[1:4] = 1
print(tensor)

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [30]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.2218, 1.2875, 0.9194],
        [2.3241, 2.5200, 2.8325],
        [2.0052, 2.5369, 2.7121],
        [0.5299, 1.4049, 0.7879],
        [1.0330, 1.7673, 1.1282]])


### 2.2 Addition: syntax 2

In [31]:
print(torch.add(x, y))

tensor([[1.2218, 1.2875, 0.9194],
        [2.3241, 2.5200, 2.8325],
        [2.0052, 2.5369, 2.7121],
        [0.5299, 1.4049, 0.7879],
        [1.0330, 1.7673, 1.1282]])


### 2.3 Addition: giving an output tensor

In [32]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.2218, 1.2875, 0.9194],
        [2.3241, 2.5200, 2.8325],
        [2.0052, 2.5369, 2.7121],
        [0.5299, 1.4049, 0.7879],
        [1.0330, 1.7673, 1.1282]])


### 2.4 Addition: in-place

adds `x`to `y`

In [33]:
y.add_(x)
print(y)

tensor([[1.2218, 1.2875, 0.9194],
        [2.3241, 2.5200, 2.8325],
        [2.0052, 2.5369, 2.7121],
        [0.5299, 1.4049, 0.7879],
        [1.0330, 1.7673, 1.1282]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [34]:
print(x[:, 1])

tensor([0.6887, 2.0000, 2.0000, 0.6406, 0.8896])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiply of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [39]:
y.mul(x)

tensor([[ 0.0852,  0.6106,  0.0029],
        [ 9.2963, 10.0800, 11.3298],
        [ 8.0208, 10.1476, 10.8486],
        [ 0.0027,  0.5765,  0.1311],
        [ 0.6281,  1.3988,  0.5138]])

In [38]:
y.mul_(x)

tensor([[0.3227, 0.8867, 0.0516],
        [4.6481, 5.0400, 5.6649],
        [4.0104, 5.0738, 5.4243],
        [0.0376, 0.9000, 0.3214],
        [0.8055, 1.5723, 0.7614]])

In [40]:
y.div(x)

tensor([[1.2218, 1.2875, 0.9194],
        [2.3241, 2.5200, 2.8325],
        [2.0052, 2.5369, 2.7121],
        [0.5299, 1.4049, 0.7879],
        [1.0330, 1.7673, 1.1282]])

In [41]:
y.div_(x)

tensor([[1.2218, 1.2875, 0.9194],
        [2.3241, 2.5200, 2.8325],
        [2.0052, 2.5369, 2.7121],
        [0.5299, 1.4049, 0.7879],
        [1.0330, 1.7673, 1.1282]])

In [19]:
torch.zeros(5).byte()

tensor([0, 0, 0, 0, 0], dtype=torch.uint8)

In [45]:
a = torch.rand(2,4)
b = torch.rand(4,2)
a.mul(b)

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [46]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [47]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.

In [48]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[ 2.  2.  2.  2.  2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [49]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [50]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machie.")

tensor([[0.2641, 0.6887, 0.0562],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.0709, 0.6406, 0.4079],
        [0.7797, 0.8896, 0.6748]], device='cuda:0')
tensor([[1.2218, 1.2875, 0.9194],
        [2.3241, 2.5200, 2.8325],
        [2.0052, 2.5369, 2.7121],
        [0.5299, 1.4049, 0.7879],
        [1.0330, 1.7673, 1.1282]], device='cuda:0')
tensor([[1.4859, 1.9761, 0.9756],
        [4.3241, 4.5200, 4.8325],
        [4.0052, 4.5369, 4.7121],
        [0.6008, 2.0455, 1.1958],
        [1.8128, 2.6570, 1.8030]], device='cuda:0')
